---
permalink: rhel-install/concept-unsupported-features-for-wfa-on-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, known, limitations 
summary: 'OnCommand Workflow Automation (WFA) 5.0 include alcune limitazioni e funzionalità non supportate che è necessario conoscere prima di installare e configurare WFA.' 
---
= Limitazioni note per OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) 5.0 include alcune limitazioni e funzionalità non supportate che è necessario conoscere prima di installare e configurare WFA.

*Autenticazione LDAP*

* Per l'autenticazione LDAP, è possibile utilizzare solo il server LDAP (Lightweight Directory Access Protocol) di Microsoft Active Directory.
* Non è necessario utilizzare un nome utente LDAP che fa parte di una struttura gerarchica di più domini per l'autenticazione o la notifica.


[NOTE]
====
Microsoft Active Directory Lightweight Directory Services (ad LDS) non è supportato.

====
*Tipi di origini dati WFA*

I tipi di origine dati di Active IQ Data Center Manager 6.0, 6.1 e 6.2 non sono più supportati nella release WFA 4.1 e questi tipi di origine dati non saranno supportati nelle release future.

*WFA installato su Linux*

* I contenuti certificati di Data ONTAP che operano in 7-Mode non sono attualmente disponibili.
* I comandi che includono solo il codice PowerShell non sono compatibili con Linux.
* I comandi certificati per 7-Mode e VMware non sono attualmente trasferiti su Perl e non sono quindi compatibili con Linux.

