---
permalink: rhel-install/task-upgrade-from-wfa-4-2.html 
sidebar: sidebar 
keywords: oncommand workflow automation, upgrade, 3.1 or later 
summary: 'È possibile eseguire un aggiornamento in-place da OnCommand Workflow Automation (Wfa) 3.1 o versione successiva all"ultima versione disponibile di Wfa per utilizzare le nuove funzionalità e i miglioramenti.' 
---
= Aggiornamento da OnCommand Workflow Automation 3.1 o versioni successive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire un aggiornamento in-place da OnCommand Workflow Automation (Wfa) 3.1 o versione successiva all'ultima versione disponibile di Wfa per utilizzare le nuove funzionalità e i miglioramenti.

.Di cosa hai bisogno
È necessario aver scaricato il file binario .bin dal NetApp Support Site sul computer host WFA.

.A proposito di questa attività
È possibile eseguire il ripristino a Wfa 5.0 solo da WFA 4.2 o 4.1. Un backup del database WFA può essere ripristinato solo su un sistema che esegue la stessa versione o una versione successiva di WFA.

Non è possibile installare MYSQL da solo quando si esegue l'aggiornamento da versioni precedenti di WFA. Puoi installare MySQL da solo:

* Quando si esegue l'aggiornamento da WFA 4.2 a versioni successive di WFA.
* Eseguire l'aggiornamento da WFA 3.1 o versioni successive scegliendo uno dei seguenti metodi:
+
** Installazione interattiva
+
... Passare a. `.bin` File binario nel computer host WFA, quindi eseguire il file.
... Per completare l'aggiornamento, seguire le istruzioni visualizzate sullo schermo.


** Installazione invisibile all'utente
+
Al prompt della shell:

+
`./WFA-version_number-build_number.bin [-y] [-u admin_user_name] [-p admin_user_password]`

+
*Esempio:*

+
`./WFA-3.1-Z3234343435.bin -y -u admin -p Company*234`

+
Durante l'aggiornamento silent, è necessario includere i valori per tutte le seguenti opzioni di comando:

+
*** `-y` ignora la conferma dell'installazione.
*** `-u` specifica il nome utente admin.
*** `-p` specifica la password dell'utente admin.
+
Se non è stata fornita la password dell'utente amministratore, è necessario immetterla quando richiesto.






